name: test

on: # NOLINT
  pull_request:
  push:
  schedule:
    - cron: '0 10 * * MON'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ros_distribution:
          - iron
          - humble
          - jazzy
          - rolling

        include:
          # Iron Irwini (May 2023 - November 2024)
          - docker_image: osrf/ros:iron-desktop-full
            ros_distribution: iron
            ros_version: 2

          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: osrf/ros:humble-desktop-full
            ros_distribution: humble
            ros_version: 2

          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: osrf/ros:jazzy-desktop-full
            ros_distribution: jazzy
            ros_version: 2

          # Rolling Ridley (No End-Of-Life)
          - docker_image: osrf/ros:rolling-desktop-full
            ros_distribution: rolling
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and test
        if: ${{ matrix.ros_version == 2 }}
        id: built-and-test
        uses: ros-tooling/action-ros-ci@v0.3
