name: test

on: # NOLINT
  pull_request:
  push:
  schedule:
    - cron: '0 10 * * MON'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ros_distribution:
          - humble
          - jazzy

        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: osrf/ros:humble-desktop-full
            ros_distribution: humble

          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: osrf/ros:jazzy-desktop-full
            ros_distribution: jazzy

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and test
        id: built-and-test
        uses: ros-tooling/action-ros-ci@v0.3
